// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System;
using System.Collections.Generic;
using Fluxzy.Misc;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    /// <summary>
    ///     Select exchanges that has image as response body.
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchanges having response content type mime matching image."
    )]
    public class ImageFilter : ResponseHeaderFilter
    {
        public ImageFilter()
            : base("image", StringSelectorOperation.Contains, "Content-Type")
        {
        }

        public override string AutoGeneratedName { get; } = "Image";

        public override Guid Identifier => (GetType().Name + Inverted).GetMd5Guid();

        public override string GenericName => "All image format";

        public override string ShortName => "img";

        public override bool PreMadeFilter => true;

        public override IEnumerable<FilterExample> GetExamples()
        {
            var defaultSample = GetDefaultSample();

            if (defaultSample != null)
                yield return defaultSample;
        }
    }
}
