// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;
using Fluxzy.Rules.Extensions;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    /// <summary>
    ///     Select exchanges having a protobuf response body. Filtering is made by inspecting value of `Content-Type` header
    ///     for `application/x-protobuf` or `application/protobuf`.
    /// </summary>
    [FilterMetaData(
        LongDescription =
            "Select exchanges having protobuf response body. The content-type header is checked to determine if the content body is protobuf."
    )]
    public class ProtobufResponseFilter : ResponseHeaderFilter
    {
        public ProtobufResponseFilter()
            : base("protobuf", StringSelectorOperation.Contains, "Content-Type")
        {
        }

        public override string AutoGeneratedName { get; } = "Protobuf response only";

        public override string GenericName => "Protobuf response only";

        public override string ShortName => "protobuf";

        public override bool PreMadeFilter => true;

        public override IEnumerable<FilterExample> GetExamples()
        {
            yield return new FilterExample(
                "Select only exchanges with protobuf response body",
                new ProtobufResponseFilter());

            yield return new FilterExample(
                "Select exchanges without protobuf response body",
                new ProtobufResponseFilter { Inverted = true });
        }
    }

    public static class ProtobufResponseFilterExtensions
    {
        /// <summary>
        ///     When response has a protobuf body. Filtering is made by inspecting value of `Content-Type` header.
        /// </summary>
        /// <param name="builder"></param>
        /// <returns></returns>
        public static IConfigureActionBuilder WhenResponseHasProtobufBody(this IConfigureFilterBuilder builder)
        {
            return builder.When(new ProtobufResponseFilter());
        }
    }
}
