// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;
using Fluxzy.Core;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    /// <summary>
    ///     Select exchanges that HTTP status code indicates a successful request (2XX)
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchanges that HTTP status code indicates a successful request (2XX)."
    )]
    public class StatusCodeSuccessFilter : Filter
    {
        public override FilterScope FilterScope => FilterScope.ResponseHeaderReceivedFromRemote;

        public override string AutoGeneratedName => "Success status code (2XX)";

        public override string GenericName => "Status code success (2XX)";

        public override string ShortName => "2XX";

        public override bool PreMadeFilter => true;

        public override bool Common { get; set; } = true;

        protected override bool InternalApply(
            ExchangeContext? exchangeContext, IAuthority authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            if (exchange == null)
                return false;

            var statusCode = exchange.StatusCode;

            return statusCode is >= 200 and < 300;
        }

        public override IEnumerable<FilterExample> GetExamples()
        {
            var defaultSample = GetDefaultSample();

            if (defaultSample != null)
                yield return defaultSample;
        }
    }
}
