using Fluxzy.Misc;
using System;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    public class ContentTypeJsonFilter : ResponseHeaderFilter
    {
        public override string AutoGeneratedName { get; } = "JSON response only";
        
        public ContentTypeJsonFilter() : base("json", StringSelectorOperation.Contains, "Content-Type")
        {
        }

        public override Guid Identifier => Guid.Parse("588C2A97-EBD2-4EF9-84F2-15664480914B");

        public override string GenericName => "JSON response only";

        public override string ShortName => "json";

        public override bool PreMadeFilter => true;
    }
}