namespace Fluxzy.Rules.Filters.ResponseFilters
{
    public class ContentTypeJsonFilter : ResponseHeaderFilter
    {
        public override string AutoGeneratedName { get; } = "JSON response only";
        
        public ContentTypeJsonFilter() : base("json", StringSelectorOperation.Contains, "Content-Type")
        {
        }

        public override string GenericName => "JSON response only";

        public override string ShortName => "json";

        public override bool PreMadeFilter => true;
    }
}