// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System;
using Fluxzy.Misc;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    /// <summary>
    ///     Select exchange that has a JSON response body.
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchange having JSON response body."
    )]
    public class ContentTypeJsonFilter : ResponseHeaderFilter
    {
        public ContentTypeJsonFilter()
            : base("json", StringSelectorOperation.Contains, "Content-Type")
        {
        }

        public override string AutoGeneratedName { get; } = "JSON response only";

        public override Guid Identifier => (GetType().Name + Inverted).GetMd5Guid();

        public override string GenericName => "JSON response only";

        public override string ShortName => "json";

        public override bool PreMadeFilter => true;

        public override bool Common { get; set; } = true;
    }
}
