// Copyright © 2022 Haga Rakotoharivelo

using System;
using Fluxzy.Misc;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    public class ImageFilter : ResponseHeaderFilter
    {
        public override string AutoGeneratedName { get; } = "Image";

        public ImageFilter() 
            : base("image", StringSelectorOperation.Contains, "Content-Type")
        {
        }

        public override Guid Identifier => (GetType().Name + Inverted).GetMd5Guid();

        public override string GenericName => "All image format";

        public override string ShortName => "img";

        public override bool PreMadeFilter => true;
    }
}