// Copyright © 2022 Haga Rakotoharivelo

using System.Collections.Generic;
using System.Linq;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    /// <summary>
    /// Select exchange according to HTTP status code
    /// </summary>
    public class StatusCodeFilter : Filter
    {
        public List<int> StatusCodes { get; set; } = new();

        public override FilterScope FilterScope => FilterScope.ResponseHeaderReceivedFromRemote;

        public override string AutoGeneratedName =>
            $"Status code among {string.Join(", ", StatusCodes.Select(s => s.ToString()))}";

        public virtual string GenericName => "Filter by status code";

        public override string ShortName => new(string.Join(",", StatusCodes.Select(s => s.ToString()))
                                                      .Take(6).ToArray());

        public override bool PreMadeFilter => true;

        protected override bool InternalApply(IAuthority authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            if (exchange == null)
                return false;

            return StatusCodes.Contains(exchange.StatusCode);
        }
    }
}
