// Copyright © 2022 Haga Rakotoharivelo

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    public class StatusCodeSuccessFilter : Filter
    {
        protected override bool InternalApply(IAuthority authority, IExchange exchange)
        {
            var statusCode = exchange.StatusCode;
            return statusCode is >= 200 and < 300; 
        }
        public override FilterScope FilterScope => FilterScope.ResponseHeaderReceivedFromRemote;

        public override string AutoGeneratedName => $"Success status code (2XX)";

        public override string GenericName => "Status code success (2XX)";

        public override string ShortName => "success";

        public override bool PreMadeFilter => true;
    }
}