using System;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    public class StatusCodeRedirectionFilter : Filter
    {
        protected override bool InternalApply(IAuthority authority, IExchange exchange)
        {
            var statusCode = exchange.StatusCode;
            return statusCode is >= 300 and < 400; 
        }

        public override Guid Identifier => Guid.Parse("8E31ECEA-AB6D-43F0-BDAC-C14FE505B6FB");

        public override FilterScope FilterScope => FilterScope.ResponseHeaderReceivedFromRemote;

        public override string AutoGeneratedName => $"Status code is redirection (3XX)";

        public override string GenericName => "Status code 3XX only";

        public override string ShortName => "3XX";

        public override bool PreMadeFilter => true;
    }
}