// Copyright © 2022 Haga Rakotoharivelo

using Fluxzy.Misc;
using System;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    public class StatusCodeSuccessFilter : Filter
    {
        protected override bool InternalApply(IAuthority? authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            if (exchange == null)
                return false;

            var statusCode = exchange.StatusCode;
            return statusCode is >= 200 and < 300; 
        }

        public override Guid Identifier => (GetType().Name + Inverted).GetMd5Guid();

        public override FilterScope FilterScope => FilterScope.ResponseHeaderReceivedFromRemote;

        public override string AutoGeneratedName => $"Success status code (2XX)";

        public override string GenericName => "Status code success (2XX)";

        public override string ShortName => "2XX";

        public override bool PreMadeFilter => true;

        public override bool Common { get; set; } = true;
    }
}