using Fluxzy.Misc;
using System;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    public class StatusCodeServerErrorFilter : Filter
    {
        protected override bool InternalApply(IAuthority authority, IExchange exchange,
            IFilteringContext? filteringContext)
        {
            var statusCode = exchange.StatusCode;
            return statusCode is >= 500 and < 600; 
        }

        public override Guid Identifier => (GetType().Name + Inverted).GetMd5Guid();

        public override FilterScope FilterScope => FilterScope.ResponseHeaderReceivedFromRemote;

        public override string AutoGeneratedName => $"Client errors (status code is 5XX)";

        public override string GenericName => "Status code 5XX only";

        public override string ShortName => "5XX";

        public override bool PreMadeFilter => true;
    }
}