// Copyright © 2022 Haga Rakotoharivelo

using System;
using System.Collections.Generic;
using System.Linq;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    public class StatusCodeFilter : Filter
    {
        protected override bool InternalApply(IAuthority? authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            if (exchange == null)
                return false;

            return StatusCodes.Contains(exchange.StatusCode); 
        }

        public List<int> StatusCodes { get; set; } = new();

        public override FilterScope FilterScope => FilterScope.ResponseHeaderReceivedFromRemote;


        public override string AutoGeneratedName => $"Status code among {string.Join(", ", StatusCodes.Select(s => s.ToString()))}";


        public override string GenericName => "Filter by status code";

        public override string ShortName => new(string.Join(",", StatusCodes.Select(s => s.ToString()))
                                                      .Take(6).ToArray());

        public override bool PreMadeFilter => true;
    }
}