using System;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    public class StatusCodeServerErrorFilter : Filter
    {
        protected override bool InternalApply(IAuthority authority, IExchange exchange)
        {
            var statusCode = exchange.StatusCode;
            return statusCode is >= 500 and < 600; 
        }

        public override Guid Identifier => Guid.Parse("213C02EC-0AC1-424A-95F7-37F6F73F716D");

        public override FilterScope FilterScope => FilterScope.ResponseHeaderReceivedFromRemote;

        public override string AutoGeneratedName => $"Client errors (status code is 5XX)";

        public override string GenericName => "Status code 5XX only";

        public override string ShortName => "5XX";

        public override bool PreMadeFilter => true;
    }
}