# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - ci
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - Semver-Minor
        - enhancement
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
