# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - ci
      - documentation
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - Semver-Minor
        - enhancement
        - new-action
        - new-filter
    - title: Other Changes
      labels:
        - "*"
    - title: Dependencies
      labels:
        - dependencies
