//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echoes.H2.Encoding.Tests.Files {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Headers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Headers() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Echoes.H2.Encoding.Tests.Files.Headers", typeof(Headers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GET /static/Resources/stylesheets/index_pri_20201013141424.min.css HTTP/1.1
        ///Host: particuliers.societegenerale.fr
        ///sec-ch-ua: &quot;Chromium&quot;;v=&quot;92&quot;, &quot; Not A;Brand&quot;;v=&quot;99&quot;, &quot;Google Chrome&quot;;v=&quot;92&quot;
        ///sec-ch-ua-mobile: ?0
        ///User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
        ///Accept: text/css,*/*;q=0.1
        ///Sec-Fetch-Site: same-origin
        ///Sec-Fetch-Mode: no-cors
        ///Sec-Fetch-Dest: style
        ///Referer: https://particuliers.societegenerale.fr/com/icd-web/cb [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Req001 {
            get {
                return ResourceManager.GetString("Req001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HTTP/1.1 200 OK
        ///Last-Modified: Tue, 08 Sep 2020 12:44:13 GMT
        ///Accept-Ranges: bytes
        ///Vary: Accept-Encoding
        ///Cache-Control: max-age=5184000
        ///Content-Type: text/css
        ///Content-Encoding: gzip
        ///Date: Thu, 25 Nov 2021 09:38:46 GMT
        ///Expires: Mon, 24 Jan 2022 08:54:01 GMT
        ///Age: 2686
        ///Content-Length: 59544
        ///
        ///.
        /// </summary>
        internal static string Resp001 {
            get {
                return ResourceManager.GetString("Resp001", resourceCulture);
            }
        }
    }
}
