// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System;
using Fluxzy.Misc;

namespace Fluxzy.Rules.Filters.ResponseFilters
{
    /// <summary>
    ///     Select exchange that has a XML response body.
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchange having XML response body."
    )]
    public class ContentTypeXmlFilter : ResponseHeaderFilter
    {
        public ContentTypeXmlFilter()
            : base("xml", StringSelectorOperation.Contains, "Content-Type")
        {
        }

        public override string AutoGeneratedName { get; } = "XML response only";

        public override Guid Identifier => (GetType().Name + Inverted).GetMd5Guid();

        public override string GenericName => "XML response only";

        public override string ShortName => "xml";

        public override bool PreMadeFilter => true;
    }
}
