// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System;
using System.Collections.Generic;
using Fluxzy.Clients.H2.Encoder;
using Fluxzy.Clients.H2.Encoder.Utils;
using Fluxzy.Core;

namespace Fluxzy.Rules.Filters
{
    public abstract class HeaderFilter : StringFilter
    {
        protected HeaderFilter(string pattern, string headerName)
            : base(pattern)
        {
            HeaderName = headerName;
        }

        protected HeaderFilter(string pattern, StringSelectorOperation operation, string headerName)
            : base(pattern, operation)
        {
            HeaderName = headerName;
        }

        [FilterDistinctive(Description = "Header name")]
        public string HeaderName { get; set; }

        public override string AutoGeneratedName => $"{HeaderName} : {base.AutoGeneratedName}";

        private protected bool MatchLiveHeader(IEnumerable<HeaderField> headers, ExchangeContext? exchangeContext)
        {
            var pattern = Pattern.EvaluateVariable(exchangeContext)!;
            var patternSpan = pattern.AsSpan();
            var comparisonType = CaseSensitive
                ? StringComparison.InvariantCulture
                : StringComparison.InvariantCultureIgnoreCase;

            foreach (var header in headers) {
                if (Http11Constants.IsNonForwardableHeader(header.Name))
                    continue;

                if (!header.Name.Span.Equals(HeaderName.AsSpan(), StringComparison.InvariantCultureIgnoreCase))
                    continue;

                if (MatchValue(header.Value.Span, patternSpan, pattern, comparisonType, exchangeContext))
                    return true;
            }

            return false;
        }
    }
}
