// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;
using Fluxzy.Rules.Extensions;
using Fluxzy.Rules.Filters.RequestFilters;
using Fluxzy.Rules.Filters.ResponseFilters;

namespace Fluxzy.Rules.Filters
{
    /// <summary>
    ///     Select exchanges having a protobuf request or response body.
    ///     Filtering is made by inspecting value of `Content-Type` header on both request and response.
    /// </summary>
    [FilterMetaData(
        LongDescription =
            "Select exchanges having a protobuf request or response body. Filtering is made by inspecting value of `Content-Type` header on both request and response."
    )]
    public class ProtobufFilter : FilterCollection
    {
        public ProtobufFilter()
            : base(new ProtobufRequestFilter(), new ProtobufResponseFilter())
        {
            Operation = SelectorCollectionOperation.Or;
        }

        public override string GenericName => "Protobuf exchange";

        public override string AutoGeneratedName { get; } = "Protobuf";

        public override string ShortName => "protobuf";

        public override bool PreMadeFilter => true;

        public override string Description => "Protobuf exchanges (request or response)";

        public override IEnumerable<FilterExample> GetExamples()
        {
            yield return new FilterExample(
                "Select exchanges with protobuf request or response body",
                new ProtobufFilter());

            yield return new FilterExample(
                "Select exchanges without any protobuf body",
                new ProtobufFilter { Inverted = true });
        }
    }

    public static class ProtobufFilterExtensions
    {
        /// <summary>
        ///     When exchange has a protobuf request or response body.
        ///     Filtering is made by inspecting value of `Content-Type` header on both request and response.
        /// </summary>
        /// <param name="builder"></param>
        /// <returns></returns>
        public static IConfigureActionBuilder WhenIsProtobuf(this IConfigureFilterBuilder builder)
        {
            return builder.When(new ProtobufFilter());
        }
    }
}
