// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using Fluxzy.Core;

namespace Fluxzy.Rules.Filters
{
    public abstract class StringFilter : Filter
    {
        protected StringFilter(string pattern)
            : this(pattern, StringSelectorOperation.Contains)
        {
            // 
        }

        protected StringFilter(string pattern, StringSelectorOperation operation)
        {
            if (operation == 0) {
                operation = StringSelectorOperation.Exact; // Hint to allow omitting default value
            }

            if (!Enum.IsDefined(typeof(StringSelectorOperation), operation))
                throw new ArgumentException("operation field is invalid or missing",
                    nameof(operation));

            Pattern = pattern;
            Operation = operation;

        }

        [FilterDistinctive(Description = "The string pattern to search")]
        public string Pattern { get; set; }

        [FilterDistinctive(Description = "The search operation performed")]
        public StringSelectorOperation Operation { get; set; } = StringSelectorOperation.Exact;

        [FilterDistinctive(Description = "true if the Search should be case sensitive")]
        public bool CaseSensitive { get; set; }

        public override string AutoGeneratedName => $"{Operation.GetDescription()} : `{Pattern}`";

        protected override bool InternalApply(
            ExchangeContext? exchangeContext, IAuthority authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            var inputList = GetMatchInputs(exchangeContext, authority, exchange);

            var comparisonType = CaseSensitive
                ? StringComparison.InvariantCulture
                : StringComparison.InvariantCultureIgnoreCase;

            var pattern = Pattern.EvaluateVariable(exchangeContext)!;
            var patternSpan = pattern.AsSpan();

            foreach (var input in inputList) {
                if (MatchValue(input, patternSpan, pattern, comparisonType, exchangeContext))
                    return true;
            }

            return false;
        }

        protected abstract IEnumerable<string> GetMatchInputs(
            ExchangeContext? exchangeContext, IAuthority authority, IExchange? exchange);

        private protected bool MatchValue(
            string value,
            ReadOnlySpan<char> pattern,
            string patternText,
            StringComparison comparisonType,
            ExchangeContext? exchangeContext)
        {
            if (Operation == StringSelectorOperation.Regex)
                return MatchRegexValue(value, pattern, patternText, exchangeContext);

            return MatchValue(value.AsSpan(), pattern, patternText, comparisonType, exchangeContext);
        }

        private protected bool MatchValue(
            ReadOnlySpan<char> value,
            ReadOnlySpan<char> pattern,
            string patternText,
            StringComparison comparisonType,
            ExchangeContext? exchangeContext)
        {
            return Operation switch {
                StringSelectorOperation.Exact => value.Equals(pattern, comparisonType),
                StringSelectorOperation.Contains => value.Contains(pattern, comparisonType),
                StringSelectorOperation.StartsWith => value.StartsWith(pattern, comparisonType),
                StringSelectorOperation.EndsWith => value.EndsWith(pattern, comparisonType),
                StringSelectorOperation.Regex => MatchRegexValue(value, pattern, patternText, exchangeContext),
                _ => throw new RuleExecutionFailureException($"Unimplemented string operation {Operation}", this)
            };
        }

        private bool MatchRegexValue(
            ReadOnlySpan<char> value,
            ReadOnlySpan<char> pattern,
            string patternText,
            ExchangeContext? exchangeContext)
        {
            var regexOptions = CaseSensitive ? RegexOptions.None : RegexOptions.IgnoreCase;

            if (pattern.DoesNotContainsCapturedRegex())
                return Regex.IsMatch(value, patternText, regexOptions);

            return MatchRegexValue(value.ToString(), pattern, patternText, exchangeContext);
        }

        private bool MatchRegexValue(
            string value,
            ReadOnlySpan<char> pattern,
            string patternText,
            ExchangeContext? exchangeContext)
        {
            var regexOptions = CaseSensitive ? RegexOptions.None : RegexOptions.IgnoreCase;

            if (pattern.DoesNotContainsCapturedRegex())
                return Regex.IsMatch(value.AsSpan(), patternText, regexOptions);

            var multiMatch = Regex.Matches(value, patternText, regexOptions);

            if (!multiMatch.Any(g => g.Success))
                return false;

            var matchedVariable = multiMatch
                                  .SelectMany(s => s.Groups.OfType<Group>())
                                  .Where(g => g.Name != "0"
                                              && g.Success && !string.IsNullOrWhiteSpace(g.Name));

            if (exchangeContext != null) {
                // If variable are present we update it
                foreach (var kp in matchedVariable) {
                    exchangeContext.VariableContext.Set($"user.{kp.Name}", kp.Value);
                }
            }

            return true;
        }
    }

    public enum SelectorCollectionOperation
    {
        Or,
        And
    }

    public enum StringSelectorOperation
    {
        [Description("equals")]
        Exact = 1,

        [Description("contains")]
        Contains,

        [Description("starts with")]
        StartsWith,

        [Description("ends with")]
        EndsWith,

        [Description("matchs (regex)")]
        Regex
    }

    public static class GenericDescriptionExtension
    {
        public static string GetDescription<T>(this T enumerationValue)
            where T : struct
        {
            var type = typeof(T);

            if (!type.IsEnum)
                throw new ArgumentException($"{nameof(enumerationValue)} must be an enum");

            var memberInfos = type.GetMember(enumerationValue.ToString()!);

            if (memberInfos.Any()) {
                var attr = memberInfos.First()
                                      .GetCustomAttributes<DescriptionAttribute>(false)
                                      .FirstOrDefault();

                if (attr != null)
                    return attr.Description;
            }

            return enumerationValue.ToString()!;
        }
    }
}
