// Copyright © 2022 Haga Rakotoharivelo

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Fluxzy.Rules.Filters.RequestFilters
{
    public class FullUrlFilter : StringFilter
    {
        public FullUrlFilter(string pattern) : base(pattern)
        {

        }

        [JsonConstructor]
        public FullUrlFilter(string pattern, StringSelectorOperation operation) : base(pattern, operation)
        {

        }

        protected override IEnumerable<string> GetMatchInputs(IAuthority authority, IExchange? exchange)
        {
            if (exchange != null )
                yield return exchange.FullUrl;
        }

        public override FilterScope FilterScope => FilterScope.RequestHeaderReceivedFromClient;

        public override string AutoGeneratedName => $"Full url {base.AutoGeneratedName}";

        public override string ShortName => "url";

        public virtual string GenericName => "Filter by full url";

        public override bool Common { get; set; } = true;
    }
}