// Copyright © 2022 Haga Rakotoharivelo

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Fluxzy.Rules.Filters.RequestFilters
{
    /// <summary>
    /// Filter according to full url (includes path and query)
    /// </summary>
    public class FullUrlFilter : StringFilter
    {
        public override FilterScope FilterScope => FilterScope.RequestHeaderReceivedFromClient;

        public override string AutoGeneratedName => $"Full url {base.AutoGeneratedName}";

        public override string ShortName => "url";

        public override bool Common { get; set; } = true;

        public FullUrlFilter(string pattern)
            : base(pattern)
        {
        }

        [JsonConstructor]
        public FullUrlFilter(string pattern, StringSelectorOperation operation)
            : base(pattern, operation)
        {
        }

        protected override IEnumerable<string> GetMatchInputs(IAuthority authority, IExchange? exchange)
        {
            if (exchange != null)
                yield return exchange.FullUrl;
        }
    }
}
