using System;
using System.Collections.Generic;
using Fluxzy.Misc;

namespace Fluxzy.Rules.Filters.RequestFilters
{
    /// <summary>
    /// Select exchange according to request method.
    /// </summary>

    [FilterMetaData(
        LongDescription = "Select exchange according to request method."
    )]
    public class MethodFilter : StringFilter
    {
        public override Guid Identifier => $"{Pattern}|{Operation}".GetMd5Guid();

        public override FilterScope FilterScope => FilterScope.RequestHeaderReceivedFromClient;

        public override string ShortName => Pattern?.ToLower() ?? "meth.";

        public override string AutoGeneratedName => $"Request method {base.AutoGeneratedName}";

        public virtual string GenericName => "Filter by HTTP method";

        public MethodFilter(string pattern)
            : base(pattern, StringSelectorOperation.Exact)
        {
        }

        protected override IEnumerable<string> GetMatchInputs(IAuthority authority, IExchange? exchange)
        {
            if (exchange != null)
                yield return exchange.Method;
        }

        protected override bool InternalApply(IAuthority authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            CaseSensitive = false;

            return base.InternalApply(authority, exchange, filteringContext);
        }
    }
}
