using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Fluxzy.Rules.Filters.RequestFilters
{
    /// <summary>
    /// Select exchange according to url path. Path includes query string if any. 
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchange according to url path. Path includes query string if any."
    )]
    public class PathFilter : StringFilter
    {
        public override FilterScope FilterScope => FilterScope.RequestHeaderReceivedFromClient;

        public override string AutoGeneratedName => $"Path `{Pattern}`";

        public override string GenericName => "Filter by url path";

        public PathFilter(string pattern)
            : base(pattern)
        {
        }

        [JsonConstructor]
        public PathFilter(string pattern, StringSelectorOperation operation)
            : base(pattern, operation)
        {
        }

        protected override IEnumerable<string> GetMatchInputs(IAuthority authority, IExchange? exchange)
        {
            if (exchange != null)
                yield return exchange.Path;
        }
    }
}
