// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;

namespace Fluxzy.Rules.Filters
{
    /// <summary>
    ///     Select exchange according to comment value
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchange having a particular comment."
    )]
    public class CommentSearchFilter : StringFilter
    {
        public CommentSearchFilter(string pattern)
            : base(pattern, StringSelectorOperation.Contains)
        {
        }

        public override FilterScope FilterScope => FilterScope.OutOfScope;

        public override string AutoGeneratedName => $"Search in comment \"{Pattern}\"";

        protected override IEnumerable<string> GetMatchInputs(IAuthority authority, IExchange? exchange)
        {
            if (exchange != null)
                yield return exchange.Comment ?? string.Empty;
        }
    }
}
