// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Linq;

namespace Fluxzy.Rules.Filters
{
    /// <summary>
    ///     Select exchanges that contain tag
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchange having tag."
    )]
    public class HasTagFilter : Filter
    {
        public override FilterScope FilterScope => FilterScope.OutOfScope;

        public override string AutoGeneratedName { get; } = "Has any tag";

        public override bool PreMadeFilter { get; } = true;

        protected override bool InternalApply(
            IAuthority authority, IExchange? exchange, IFilteringContext? filteringContext)
        {
            return exchange?.Tags?.Any() ?? false;
        }
    }
}
