// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Fluxzy.Rules.Filters
{
    /// <summary>
    ///     Select exchanges according to upstream ip address
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchange according to upstream IP address. Full IP notation is used from IPv6."
    )]
    public class IpEgressFilter : StringFilter
    {
        public IpEgressFilter(string pattern)
            : base(pattern)
        {
        }

        [JsonConstructor]
        public IpEgressFilter(string pattern, StringSelectorOperation operation)
            : base(pattern, operation)
        {
        }

        public override FilterScope FilterScope => FilterScope.OnAuthorityReceived;

        public override string GenericName => "Filter by Egress IP Address";

        public override string AutoGeneratedName => $"IP : `{Pattern}`";

        public override string ShortName => "ip";

        protected override IEnumerable<string> GetMatchInputs(IAuthority authority, IExchange? exchange)
        {
            yield return exchange?.EgressIp ?? string.Empty;
        }
    }
}
