// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

namespace Fluxzy.Rules.Filters
{
    /// <summary>
    ///     Select exchange according to tag values
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchange having tags matching specified condition."
    )]
    public class TagContainsFilter : Filter
    {
        public TagContainsFilter(Tag? tag)
        {
            Tag = tag;
        }

        public Tag? Tag { get; }

        public override FilterScope FilterScope => FilterScope.OutOfScope;

        public override string AutoGeneratedName => $"Tag contains {Tag?.Value}";

        protected override bool InternalApply(
            IAuthority authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            if (exchange?.Tags == null || Tag == null)
                return false;

            return exchange.Tags.Contains(Tag);
        }
    }
}
