// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;

namespace Fluxzy.Rules.Filters
{
    /// <summary>
    ///     Select exchanges according to tag values
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchanges having tags matching specified condition.",
        NotSelectable = true
    )]
    public class TagContainsFilter : Filter
    {
        public TagContainsFilter(Tag? tag)
        {
            Tag = tag;
        }

        public Tag? Tag { get; }

        public override FilterScope FilterScope => FilterScope.OutOfScope;

        public override string AutoGeneratedName => $"Tag contains {Tag?.Value}";

        protected override bool InternalApply(
            IAuthority authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            if (exchange?.Tags == null || Tag == null)
                return false;

            return exchange.Tags.Contains(Tag);
        }

        public override IEnumerable<FilterExample> GetExamples()
        {
            // Outofscope filter does not include examples
            yield break;
        }
    }
}
