using System.Collections.Generic;

namespace Fluxzy.Rules.Filters
{
    /// <summary>
    /// Select exchange according to comment value
    /// </summary>
    public class CommentSearchFilter : StringFilter
    {
        public override FilterScope FilterScope => FilterScope.OutOfScope;

        public override string AutoGeneratedName => $"Search in comment \"{Pattern}\"";

        public CommentSearchFilter(string pattern)
            : base(pattern, StringSelectorOperation.Contains)
        {
        }

        protected override IEnumerable<string> GetMatchInputs(IAuthority authority, IExchange? exchange)
        {
            if (exchange != null)
                yield return exchange.Comment ?? string.Empty;
        }
    }
}
