using System.Collections.Generic;

namespace Fluxzy.Rules.Filters
{
    public class CommentSearchFilter : StringFilter
    {
        public CommentSearchFilter(string pattern)
            : base(pattern, StringSelectorOperation.Contains)
        {

        }

        public override FilterScope FilterScope => FilterScope.OutOfScope;

        protected override IEnumerable<string> GetMatchInputs(IAuthority authority, IExchange? exchange)
        {
            if (exchange != null) {
                yield return exchange.Comment ?? string.Empty; 
            }
        }

        public override string AutoGeneratedName => $"Search in comment \"{Pattern}\"";
    }
}