// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using Fluxzy.Clients;

namespace Fluxzy.Rules.Filters
{
    [FilterMetaData(
        LongDescription = "Select exchange having a specific connection id.",
        NotSelectable = true
    )]
    public class ConnectionFilter : Filter
    {
        public ConnectionFilter(int connectionId)
        {
            ConnectionId = connectionId;
        }

        public override FilterScope FilterScope => FilterScope.ResponseHeaderReceivedFromRemote;

        public int ConnectionId { get; set; }

        public override string ShortName => $"con. #{ConnectionId}";

        public override string AutoGeneratedName => $"Same connection ##{ConnectionId}";

        protected override bool InternalApply(
            IAuthority authority, IExchange? exchange, IFilteringContext? filteringContext)
        {
            if (exchange == null)
                return false;

            if (exchange is Exchange originalExchange)
                return originalExchange.Connection?.Id == ConnectionId;

            if (exchange is ExchangeInfo exchangeInfo)
                return exchangeInfo.ConnectionId == ConnectionId;

            return false;
        }
    }
}
