// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

namespace Fluxzy.Rules.Filters
{
    /// <summary>
    ///     Select exchanges that contain comment
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchange having comment."
    )]
    public class HasCommentFilter : Filter
    {
        public override FilterScope FilterScope => FilterScope.OutOfScope;

        public override string AutoGeneratedName => "Has any comment";

        public override bool PreMadeFilter => true;

        protected override bool InternalApply(
            IAuthority authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            return !string.IsNullOrWhiteSpace(exchange?.Comment);
        }
    }
}
