// Copyright © 2022 Haga RAKOTOHARIVELO

namespace Fluxzy.Rules.Filters
{
    public class TagContainsFilter : Filter
    {
        public Tag? Tag { get; }

        public override FilterScope FilterScope => FilterScope.OutOfScope;

        public override string AutoGeneratedName => $"Tag contains {Tag?.Value}";

        public TagContainsFilter(Tag? tag)
        {
            Tag = tag;
        }

        protected override bool InternalApply(IAuthority? authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            if (exchange?.Tags == null || Tag == null)
                return false;

            return exchange.Tags.Contains(Tag);
        }
    }
}
