// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;
using Fluxzy.Core;
using Fluxzy.Rules.Extensions;

namespace Fluxzy.Rules.Filters.RequestFilters
{
    /// <summary>
    ///     Select gRPC exchanges only. Filtering is made by inspecting value of `Content-Type` header
    ///     for `application/grpc` prefix.
    /// </summary>
    [FilterMetaData(
        LongDescription =
            "Select gRPC exchanges only. Filtering is made by inspecting value of `Content-Type` header."
    )]
    public class IsGrpcFilter : RequestHeaderFilter
    {
        public IsGrpcFilter()
            : base("application/grpc", StringSelectorOperation.StartsWith, "content-type")
        {
        }

        public override FilterScope FilterScope => FilterScope.RequestHeaderReceivedFromClient;

        public override string GenericName => "gRPC only";

        public override string AutoGeneratedName { get; } = "gRPC only";

        public override string ShortName => "grpc";

        public override bool PreMadeFilter => true;

        public override IEnumerable<FilterExample> GetExamples()
        {
            yield return new FilterExample(
                "Select only gRPC exchanges",
                new IsGrpcFilter());

            yield return new FilterExample(
                "Select all non-gRPC exchanges",
                new IsGrpcFilter { Inverted = true });
        }
    }

    public static class IsGrpcFilterExtensions
    {
        /// <summary>
        ///     When request is a gRPC call. Filtering is made by inspecting value of `Content-Type` header.
        /// </summary>
        /// <param name="builder"></param>
        /// <returns></returns>
        public static IConfigureActionBuilder WhenIsGrpc(this IConfigureFilterBuilder builder)
        {
            return builder.When(new IsGrpcFilter());
        }
    }
}
