// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

namespace Fluxzy.Rules.Filters.RequestFilters
{
    [FilterMetaData(
        LongDescription =
            "Select request sending 'multipart/form-data' body. Filtering is made by inspecting value of `Content-Type` header"
    )]
    public class MultipartDataRequestFilter : RequestHeaderFilter
    {
        public MultipartDataRequestFilter()
            : base("multipart/form-data", StringSelectorOperation.Contains, "content-type")
        {
        }
        
        public override FilterScope FilterScope => FilterScope.RequestHeaderReceivedFromClient;
        
        public override string GenericName => "Has a request body multipart data";

        public override string AutoGeneratedName { get; } = "Multipart data";

        public override string ShortName => "mtp .data";

        public override bool PreMadeFilter => true;
    }
}
