// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;
using Fluxzy.Core;

namespace Fluxzy.Rules.Filters.RequestFilters
{
    /// <summary>
    ///     Select exchanges initiated by a process with the specified process ID.
    /// </summary>
    [FilterMetaData(
        LongDescription = "Select exchanges initiated by a process with the specified process ID. " +
                          "Process tracking must be enabled and the connection must originate from localhost."
    )]
    public class ProcessIdFilter : Filter
    {
        public ProcessIdFilter()
        {
        }

        public ProcessIdFilter(int processId)
        {
            ProcessId = processId;
        }

        [FilterDistinctive(Description = "The process ID to match")]
        public int ProcessId { get; set; }

        public override FilterScope FilterScope => FilterScope.RequestHeaderReceivedFromClient;

        public override string AutoGeneratedName => $"Process ID `{ProcessId}`";

        public override string GenericName => "Filter by process ID";

        public override string ShortName => "pid";

        protected override bool InternalApply(
            ExchangeContext? exchangeContext,
            IAuthority authority,
            IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            if (exchange is not Exchange internalExchange)
                return false;

            var processInfo = internalExchange.ProcessInfo;

            if (processInfo == null)
                return false;

            return processInfo.ProcessId == ProcessId;
        }

        public override IEnumerable<FilterExample> GetExamples()
        {
            yield return new FilterExample(
                "Filter traffic from process with ID 1234",
                new ProcessIdFilter(1234));
        }
    }
}
