// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;
using Fluxzy.Core;
using Fluxzy.Rules.Extensions;

namespace Fluxzy.Rules.Filters.RequestFilters
{
    /// <summary>
    ///     Select requests sending a protobuf body. Filtering is made by inspecting value of `Content-Type` header
    ///     for `application/x-protobuf` or `application/protobuf`.
    /// </summary>
    [FilterMetaData(
        LongDescription =
            "Select requests sending a protobuf body. Filtering is made by inspecting value of `Content-Type` header."
    )]
    public class ProtobufRequestFilter : RequestHeaderFilter
    {
        public ProtobufRequestFilter()
            : base("protobuf", StringSelectorOperation.Contains, "content-type")
        {
        }

        public override FilterScope FilterScope => FilterScope.RequestBodyReceivedFromClient;

        public override string GenericName => "Has a request body protobuf";

        public override string AutoGeneratedName { get; } = "Protobuf request body";

        public override string ShortName => "snt. protobuf";

        public override bool PreMadeFilter => true;

        public override IEnumerable<FilterExample> GetExamples()
        {
            yield return new FilterExample(
                "Select only exchanges with protobuf request body",
                new ProtobufRequestFilter());

            yield return new FilterExample(
                "Select exchanges without protobuf request body",
                new ProtobufRequestFilter { Inverted = true });
        }
    }

    public static class ProtobufRequestFilterExtensions
    {
        /// <summary>
        ///     When request has a protobuf body. Filtering is made by inspecting value of `Content-Type` header.
        /// </summary>
        /// <param name="builder"></param>
        /// <returns></returns>
        public static IConfigureActionBuilder WhenRequestHasProtobufBody(this IConfigureFilterBuilder builder)
        {
            return builder.When(new ProtobufRequestFilter());
        }
    }
}
