// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;
using Fluxzy.Clients;

namespace Fluxzy.Rules.Filters.RequestFilters
{
    [FilterMetaData(
        LongDescription =
            "Select exchanges according to configured source agent (user agent or process) with a regular string search."
    )]
    public class AgentLabelFilter : StringFilter
    {
        public AgentLabelFilter(string pattern)
            : base(pattern, StringSelectorOperation.Exact)
        {
        }

        public override FilterScope FilterScope { get; } = FilterScope.RequestHeaderReceivedFromClient;

        public override string GenericName => "Agent filter";

        public override string AutoGeneratedName => $"Agent {Pattern}";

        public override string ShortName => "agent label";

        protected override IEnumerable<string> GetMatchInputs(
            ExchangeContext? exchangeContext, IAuthority authority, IExchange? exchange)
        {
            if (exchange?.Agent?.FriendlyName == null)
                yield break;

            yield return exchange.Agent.FriendlyName;
        }

        public override IEnumerable<FilterExample> GetExamples()
        {
            yield return new FilterExample(
                "Retains only exchanges with the exact agent label",
                new AgentLabelFilter("Chrome"));
        }
    }
}
