// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System;
using System.Collections.Generic;
using System.Linq;
using Fluxzy.Clients.H2.Encoder;
using Fluxzy.Core;
using Fluxzy.Formatters.Producers.Requests;

namespace Fluxzy.Rules.Filters.RequestFilters
{
    [FilterMetaData(
        LongDescription = "Exchange having a request cookie with a specific name"
    )]
    public class HasCookieOnRequestFilter : StringFilter
    {
        public HasCookieOnRequestFilter(string cookieName, string pattern)
            : base(pattern)
        {
            Name = cookieName;
        }

        [FilterDistinctive(Description = "Cookie name", DefaultValue = "")]
        public string Name { get; set; }

        public override string AutoGeneratedName => "Request cookie value";

        public override string GenericName => "Cookie";

        public override string ShortName => "cookie";

        public override bool PreMadeFilter => false;

        public override FilterScope FilterScope => FilterScope.RequestHeaderReceivedFromClient;

        public override IEnumerable<FilterExample> GetExamples()
        {
            yield return new FilterExample(
                "Select only filter having a request cookie with name `JSESSIONID`",
                new HasCookieOnRequestFilter("JSESSIONID", "") {
                    Operation = StringSelectorOperation.Regex
                });
        }

        protected override IEnumerable<string> GetMatchInputs(
            ExchangeContext? exchangeContext, IAuthority authority, IExchange? exchange)
        {
            if (exchange == null)
                yield break;

            var requestCookies = HttpHelper.ReadRequestCookies(
                exchange.GetRequestHeaders().Select(h => (GenericHeaderField) h));

            foreach (var cookie in requestCookies) {
                if (cookie.Name.Equals(Name.EvaluateVariable(exchangeContext), StringComparison.OrdinalIgnoreCase))
                    yield return cookie.Value;
            }
        }
    }
}
