// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

using System.Collections.Generic;
using System.Text.Json.Serialization;
using Fluxzy.Core;

namespace Fluxzy.Rules.Filters.RequestFilters
{
    /// <summary>
    ///     Select exchanges according to host. The host is taken from the Host header (HTTP/1.1) or the :authority header
    ///     (H2).
    /// </summary>
    [FilterMetaData(
        LongDescription =
            "Select exchanges according to hostname (excluding port). To select authority (combination of host:port), use <goto>AuthorityFilter</goto>."
    )]
    public class HostFilter : StringFilter
    {
        public HostFilter(string pattern)
            : this(pattern, StringSelectorOperation.Exact)
        {
        }

        [JsonConstructor]
        public HostFilter(string pattern, StringSelectorOperation operation)
            : base(pattern, operation)
        {
        }

        public override FilterScope FilterScope => FilterScope.OnAuthorityReceived;

        public override string? ShortName => "host";

        public override string AutoGeneratedName => $"Hostname `{Pattern}`";

        public override string GenericName => "Filter by host";

        public override bool Common { get; set; } = true;

        public override IEnumerable<FilterExample> GetExamples()
        {
            yield return new FilterExample(
                "Retains only exchanges with the exact host",
                new HostFilter("www.fluxzy.io", StringSelectorOperation.Exact));

            yield return new FilterExample(
                "Retains only exchanges with a host matching the regex",
                new HostFilter(@"^www\.fluxzy\.io$", StringSelectorOperation.Regex));
        }

        protected override IEnumerable<string> GetMatchInputs(
            ExchangeContext? exchangeContext, IAuthority authority, IExchange? exchange)
        {
            var hostName = authority?.HostName ?? exchange?.KnownAuthority;

            if (hostName != null)
                yield return hostName;
        }
    }
}
