// Copyright 2021 - Haga Rakotoharivelo - https://github.com/haga-rak

namespace Fluxzy.Rules.Filters.RequestFilters
{
    [FilterMetaData(
        LongDescription = "Select request sending JSON body. Filtering is made by inspecting value of `Content-Type` header"
    )]
    public class JsonRequestFilter : RequestHeaderFilter
    {
        public JsonRequestFilter()
            : base("json", StringSelectorOperation.Contains, "content-type")
        {

        }

        public override FilterScope FilterScope => FilterScope.RequestBodyReceivedFromClient;

        public override string GenericName => "Has a request body JSON";

        public override string AutoGeneratedName { get; } = "JSON request body";

        public override string ShortName => "snt. json";

        public override bool PreMadeFilter => true;

        protected override bool InternalApply(
            IAuthority authority, IExchange? exchange,
            IFilteringContext? filteringContext)
        {
            return filteringContext?.HasRequestBody ?? false;
        }
    }
}
