using System.Reactive.Linq;
using System.Reactive.Subjects;
using Fluxzy.Desktop.Services.Models;
using Fluxzy.Rules.Filters;
using Fluxzy.Rules.Filters.RequestFilters;
using Fluxzy.Utils;

namespace Fluxzy.Desktop.Services.ContextualFilters
{
    internal class ContextualFilterBuilder : ObservableProvider<ContextualFilterResult>
    {
        protected override BehaviorSubject<ContextualFilterResult> Subject { get; } = new(new());
        
        public ContextualFilterBuilder(IObservable<TrunkState> trunkStateObservable)
        {
            trunkStateObservable
                .Select(Build)
                .Do(t => Subject.OnNext(t))
                .Subscribe(); 
        }

        private ContextualFilterResult Build(TrunkState trunkState)
        {
            var result = new ContextualFilterResult();

            // Most used hostname 

            var mostUsedHostNames = trunkState.Exchanges
                                    .GroupBy(r => r.ExchangeInfo.KnownAuthority)
                                    .OrderByDescending(r => r.Count())
                                    .Take(100)
                                    .SelectMany(r => GenerateAllFilters(r.Key, r.Count() + 10))
                                    .DistinctBy(t => t.Filter.AutoGeneratedName);

            result.ContextualFilters.AddRange(mostUsedHostNames);

            // Most used 
            
            // Here we trigger the contextual filter

            return result;
        }

        private static IEnumerable<ContextualFilter> GenerateAllFilters(string host, int weight)
        {
            yield return new ContextualFilter(new HostFilter(host, StringSelectorOperation.Exact), weight);

            if (SubdomainUtility.TryGetSubDomain(host, out var subDomain))
                yield return new ContextualFilter(new HostFilter(subDomain!, StringSelectorOperation.EndsWith) {
                    Description = $"Subdomain : *.{subDomain}"
                }, weight);


        }

    }


    public class ContextualFilterResult
    {
        public List<ContextualFilter> ContextualFilters { get; } = new(); 


    }

    public class ContextualFilter
    {
        public ContextualFilter(Filter filter, int weight)
        {
            Filter = filter;
            Weight = weight;
        }

        public Filter Filter { get;  }
        
        public int Weight { get; }
    }

}
