name: Build and tests Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, Windows]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore fluxzy
    - name: Build
      run: dotnet build fluxzy --no-restore
    - name: Test
      run: dotnet test Fluxzy.Tests -e EnableDumpStackTraceOn502=true
