name: Build and tests Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, Linux]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN || github.token }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name : Remove previous package source
      run: dotnet nuget remove source githubhaga
    - name : Add package nuget source
      run: dotnet nuget add source --username haga-rak --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name githubhaga "https://nuget.pkg.github.com/haga-rak/index.json"
    - name: Restore dependencies of tests
      run: dotnet restore Fluxzy.Tests
    - name: Restore dependencies
      run: dotnet restore Fluxzy
    - name: Build
      run: dotnet build Fluxzy --no-restore
    - name: Test
      run: dotnet test Fluxzy.Tests -e EnableDumpStackTraceOn502=true
