name: Publish NuGet packages

on: workflow_dispatch

jobs:
  publish-release:
    name: "Publish release"
    strategy:
      matrix:
        osversion: [Windows]
        ostype: ['self-hosted']

    runs-on: ${{ matrix.osversion }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Publish to private Nugets
      shell: bash
      run: ./build.sh fluxzy-publish-nuget
