name: Publish NuGet packages

on: workflow_dispatch

jobs:
  publish-release:
    name: "Publish release"
    strategy:
      matrix:
        osversion: [Windows]
        ostype: ['self-hosted']

    runs-on: ${{ matrix.osversion }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Publish to private Nugets
      shell: bash
      env:
        TOKEN_FOR_NUGET : ${{ secrets.TOKEN_FOR_NUGET }}
        PARTNER_SECRET : ${{ secrets.PARTNER_SECRET }}
        
        AZURE_VAULT_DESCRIPTION_URL : ${{ secrets.AZURE_VAULT_DESCRIPTION_URL }}
        AZURE_VAULT_URL : ${{ secrets.AZURE_VAULT_URL }}
        AZURE_VAULT_CERTIFICATE : ${{ secrets.AZURE_VAULT_CERTIFICATE }}
        AZURE_VAULT_CLIENT_ID : ${{ secrets.AZURE_VAULT_CLIENT_ID }}
        AZURE_VAULT_CLIENT_SECRET : ${{ secrets.AZURE_VAULT_CLIENT_SECRET }}
        AZURE_VAULT_TENANT_ID : ${{ secrets.AZURE_VAULT_TENANT_ID }}

      run: bash build.sh -- fluxzy-publish-nuget
