name: Publish NuGet (PUBLIC!) (PRERELEASE!)

on: workflow_dispatch

# No author signature on nuget.org packages, see release-nuget.public.yml.
jobs:
  publish-release:
    name: "Publish pre-release"
    strategy:
      matrix:
        osversion: [Windows]
        ostype: ['self-hosted']
      fail-fast: false

    runs-on: ${{ matrix.osversion }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x
    - name: Publish pre-release to nuget.org
      shell: bash
      env:
        TOKEN_FOR_NUGET : ${{ secrets.TOKEN_FOR_NUGET }}
        GH_RELEASE_TOKEN : ${{ secrets.GH_RELEASE_TOKEN }}
        REPOSITORY_OWNER : ${{ github.repository_owner }}
        REPOSITORY_NAME : ${{ github.event.repository.name }}
        PARTNER_SECRET : ${{ secrets.PARTNER_SECRET }}
        NUGET_ORG_API_KEY : ${{ secrets.NUGET_ORG_API_KEY }}

      run: bash build.sh fluxzy-publish-nuget-public-pre-release
