name: Publish NuGet packages

on: workflow_dispatch

jobs:
  publish-release:
    name: "Publish release"
    strategy:
      matrix:
        osversion: [Windows]
        ostype: ['self-hosted']

    runs-on: ${{ matrix.osversion }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Add nuget package source 
      continue-on-error: true  # ignore error (package source already present on the runner)
      run: dotnet nuget add source https://nuget.pkg.github.com/haga-rak/index.json -n nuget-fluxy -u haga-rak -p ${{ secrets.TOKEN_FOR_NUGET }}

    - name: Install dotnet script
      continue-on-error: true  # ignore error (dotnet script already present on the runner)
      run: dotnet tool install --global dotnet-script

    - name: Install nbgv
      continue-on-error: true  # ignore error (dotnet nbgv already present on the runner)
      run: dotnet tool install --global nbgv

    - name: Install dotnet-sign
      continue-on-error: true  # ignore error (dotnet sign already present on the runner)
      run: dotnet tool install --global sign --version 0.9.1-beta.23356.1

    - name: Test
      run: dotnet test test/Fluxzy.Tests -e EnableDumpStackTraceOn502=true --logger "trx;logfilename=fluxzytests.trx" --results-directory ./TestResults/Fluxzy

    - name: Packaging Fluxzy
      shell: cmd
      run: dotnet build -c Release src/Fluxzy.Core && dotnet pack --include-symbols -c Release src/Fluxzy.Core -o _npkgout

    - name: Packaging Fluxzy.Interop.Pcap
      shell: cmd
      run: dotnet build -c Release src/Fluxzy.Interop.Pcap && dotnet pack --include-symbols -c Release src/Fluxzy.Interop.Pcap -o _npkgout
    
    - name: Sign packages
      shell: cmd
      working-directory: _npkgout
      run: >
        sign code azure-key-vault \
            *.nupkg \
            --publisher-name "Fluxzy SAS" \
            --description "Fluxzy Signed" \
            --description-url "${{secrets.AZURE_VAULT_DESCRIPTION_URL}}" \
            --azure-key-vault-url "${{secrets.AZURE_VAULT_URL}}" \
            --azure-key-vault-certificate "${{secrets.AZURE_VAULT_CERTIFICATE}}" \
            --azure-key-vault-client-id "${{secrets.AZURE_VAULT_CLIENT_ID}}" \
            --azure-key-vault-client-secret "${{secrets.AZURE_VAULT_CLIENT_SECRET}}" \
            --azure-key-vault-tenant-id "${{secrets.AZURE_VAULT_TENANT_ID}}"

    - name: Push
      working-directory: _npkgout
      run: dotnet nuget push *.nupkg --skip-duplicate --api-key ${{secrets.TOKEN_FOR_NUGET}} --source https://nuget.pkg.github.com/haga-rak/index.json
